/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"
#include <unistd.h>

char* compute_1(char *host, char login[], char password[], char cmd[], int auth_chk) {
	CLIENT *clnt;
	char **result_1;
	command  execute_1_arg;
	char **result_2;
	userdata  auth_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, COMPUTE, EXECUTE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	strcpy(auth_1_arg.login,login);
	strcpy(auth_1_arg.password, password);
	if (!auth_chk){
		execute_1_arg.data = auth_1_arg;
		strcpy(execute_1_arg.cmd, cmd);
		result_1 = execute_1(&execute_1_arg, clnt);
		if (result_1 == (char **)NULL) {
			clnt_perror (clnt, "call failed");
		}
		return *result_1;
	} else {
		result_2 = auth_1(&auth_1_arg, clnt);
		if (result_2 == (char **)NULL) {
			clnt_perror (clnt, "call failed");
		}
		if(!strcmp(*result_2, "authorized")){
			return 1;
		} else {
			return 0;
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char login[32], password[32], cmd[256];

	if (argc < 2) {
		printf ("[RPC_shell_client]\nUsage: %s server_host\n", argv[0]);
		exit (1);
	}

	printf("Enter login: ");
	scanf("%[^\n]%*c", login);
	printf("Enter password: ");
	scanf("%[^\n]%*c", password);
	host = argv[1];

	if(compute_1(host, login, password, 0, 1)){
		printf("Logged in successfully!\n");
	} else {
		printf("Invalid login/password!\n");
		exit(0);
	}
	printf("[RPC_shell_client]\nStatus: loading...");
	printf("\nStatus: online\nWelcome, %s\nUse command 'disconnect' to close the shell!\n", login);
	while (1) {
		printf("%s@rpcshell: ", login);
		scanf("%[^\n]%*c", &cmd);
		if(!strcmp(cmd, "disconnect")){
			printf("Status: offline...");
			exit(0);
		} else {
			printf("%s", compute_1(host, login, password, cmd, 0));
		}
	}

	exit (0);
}
