/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "IDL.h"

bool_t
xdr_userdata (XDR *xdrs, userdata *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->login, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->password, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_command (XDR *xdrs, command *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->cmd, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_userdata (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}
